apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-calculator
spec:
  selector:
    matchLabels:
      app: drift-calculator
  replicas: 1
  template:
    metadata:
      labels:
        app: drift-calculator
    spec:
      containers:
        - name: drift-calculator
          image: drift-calculator
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
